baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test Site'
theme = 'hugo-theme-itheme'
paginate = 5
[params]
  defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
  email = 'test@test.com'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/test'
  [[params.socialMedia]]
    name = 'Twitter'
    url = 'https://twitter.com/test'
  [[params.blogroll]]
    name = 'Blogroll ??'
    url = 'Blog Link'
  [[params.blogroll]]
    name = 'Apple'
    url = 'https://apple.com/'
